export const CHURCH = {
  nameEn: "Boston Milal Korean Church",
  nameKo: "보스톤밀알한인장로교회",
  address: "15 Alpha Road, Chelmsford, MA 01824",
  addressLine1: "15 Alpha Road",
  addressLine2: "Chelmsford, MA 01824",
  geo: { lat: 42.5928872, lng: -71.3260446 }, // OSM Nominatim for 15 Alpha Road, Chelmsford, MA 01824
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=15+Alpha+Road%2C+Chelmsford%2C+MA+01824",
  affiliationEn: "KAPC · New England Presbytery",
  affiliationKo: "KAPC · 뉴잉글랜드노회",
  mottoYear: "2026",
  mottoKo: "선한 청지기 같이 서로 봉사하라",
  mottoRef: "벧전 4:10",
  mottoEn: "Serve one another as good stewards",
  mottoRefEn: "1 Peter 4:10",
  pastorNameKo: "권혁진 목사",
  pastorNameEn: "Rev. Hyukjin Kwon",
  youtubeHandle: "@milalkoreanchurch1435",
  youtubeUrl: "https://www.youtube.com/@milalkoreanchurch1435",
  facebookHandle: "milalchurch",
  facebookUrl: "https://www.facebook.com/milalchurch/",
  sundayWorshipEn: "Sunday 10:00 AM",
  sundayWorshipKo: "주일 오전 10:00",
  koreanSchoolTimeEn: "Sundays 9:30-10:30 AM (spring/fall semesters)",
  koreanSchoolTimeKo: "매주 주일 오전 9:30-10:30 (봄·가을 학기)",
  mottoTbd: false,
  pastorTbd: true,
  koreanSchoolTimeTbd: true,
} as const;

/** Real photos from the old Weebly site (bostonmilalchurch.org). */
export const PHOTOS = {
  logo: "/images/logo.png",
  pastor: "/images/pastor.jpg",
  worship: "/images/worship.jpg",
  congregation: "/images/congregation.jpg",
  children: "/images/children.jpg",
  youth: "/images/youth.jpg",
  koreanSchool: "/images/korean-school.jpg",
} as const;

export const WORSHIP_ROWS = [
  {
    key: "sunday",
    timeEn: "Sunday 10:00 AM",
    timeKo: "주일 오전 10:00",
    placeEn: "Main sanctuary",
    placeKo: "대예배실",
    tbd: false,
  },
  {
    key: "friday",
    timeEn: "1st & 3rd Fridays 7:30 PM",
    timeKo: "매월 첫째·셋째 주 금요일 오후 7:30",
    placeEn: "",
    placeKo: "",
    tbd: false,
  },
  {
    key: "intercession",
    timeEn: "Sunday 9:00 AM",
    timeKo: "주일 오전 9:00",
    placeEn: "",
    placeKo: "",
    tbd: false,
  },
  {
    key: "cell",
    timeEn: "First Sunday each month",
    timeKo: "매월 첫째 주일",
    placeEn: "",
    placeKo: "",
    tbd: false,
  },
  {
    key: "children",
    timeEn: "Sunday 10:00 AM",
    timeKo: "주일 오전 10:00",
    placeEn: "Children's room",
    placeKo: "유치부실",
    tbd: true,
  },
  {
    key: "youth",
    timeEn: "Sunday 10:00 AM",
    timeKo: "주일 오전 10:00",
    placeEn: "Youth room",
    placeKo: "중고등부실",
    tbd: true,
  },
] as const;

export const GENERATIONS_ROWS = [
  {
    key: "toddlers",
    ageEn: "Young children",
    ageKo: "어린이",
    timeEn: "Sunday 10:00 AM",
    timeKo: "주일 오전 10:00",
    placeEn: "Children's room",
    placeKo: "유치부실",
    tbd: true,
  },
  {
    key: "elementary",
    ageEn: "Elementary",
    ageKo: "초등",
    timeEn: "",
    timeKo: "",
    placeEn: "",
    placeKo: "",
    tbd: true,
  },
  {
    key: "youth",
    ageEn: "Middle & high school",
    ageKo: "중고등",
    timeEn: "Sunday 10:00 AM",
    timeKo: "주일 오전 10:00",
    placeEn: "Youth room",
    placeKo: "중고등부실",
    tbd: true,
  },
  {
    key: "youngAdults",
    ageEn: "Young adults",
    ageKo: "청년",
    timeEn: "",
    timeKo: "",
    placeEn: "",
    placeKo: "",
    tbd: true,
  },
] as const;
